### ISSUE TITLE
undefineds and nulls get erased in method return type

### ISSUE THREAD

**Issue by bogeeee** [typescript-rtti/typescript-rtti#111]
_Damn, i hit the enter key - the title must say:_  **undefineds and nulls get erased in method return type**

Here's a reconstruction, thx to the nice playground ;)

```
import { reflect } from 'typescript-rtti';

class A {
    foo() : number | undefined { return 123; }
}

console.log(reflect(A).getMethod('foo').returnType); // Got: "class Number", expected: "class Number | undefined"
console.log(reflect(A).getMethod('foo').returnType.matchesValue(undefined)); // Got: false, expected: true
```

**Comment by bogeeee** [comment]
Update: it seems, not only in return types but everywhere: Parameters, deep parameters. Please update the title. 
This is imho a big functionality breaker. Here's another one:

```
import { reflect } from 'typescript-rtti';

class A {
    foo(param : {deep: string | null | undefined | number}) {};
}

console.log(reflect(A).getMethod('foo').parameters[0].type.toString()); // Got "{ deep: [class String | class Number] }", expected: { deep: [class String | undefined | null | class Number] }

```

**Comment by rezonant** [comment]
https://github.com/typescript-rtti/typescript-rtti?tab=readme-ov-file#q-looks-like-it-doesnt-emit-number--null-as-expected-im-getting-number

> Typescript's strictNullChecks setting is the cause

In the playground, you'll need to add `{ "strictNullChecks": true }`, [as seen here](https://typescript-rtti.org/#fFYyfHsic291cmNlIjoiaW1wb3J0IHsgcmVmbGVjdCB9IGZyb20gJ3R5cGVzY3JpcHQtcnR0aSc7XG5cbmNsYXNzIEEge1xuICAgIGZvbygpIDogbnVtYmVyIHwgdW5kZWZpbmVkIHsgcmV0dXJuIDEyMzsgfVxufVxuXG5jb25zb2xlLmxvZyhyZWZsZWN0KEEpLmdldE1ldGhvZCgnZm9vJykucmV0dXJuVHlwZSk7IC8vIEdvdDogXCJjbGFzcyBOdW1iZXJcIiwgZXhwZWN0ZWQ6IFwiY2xhc3MgTnVtYmVyIHwgdW5kZWZpbmVkXCJcbmNvbnNvbGUubG9nKHJlZmxlY3QoQSkuZ2V0TWV0aG9kKCdmb28nKS5yZXR1cm5UeXBlLm1hdGNoZXNWYWx1ZSh1bmRlZmluZWQpKTsgLy8gR290OiBmYWxzZSwgZXhwZWN0ZWQ6IHRydWUiLCJjb21waWxlck9wdGlvbnMiOiJ7XHJcbiAgICBcInN0cmljdE51bGxDaGVja3NcIjogdHJ1ZVxyXG59In0=)

**Comment by rezonant** [comment]
Closing in favor of #19 
See also:
- #80
