### ISSUE TITLE
Reflect on whether a TypeRef is explicit

### ISSUE THREAD

**Issue by capaj** [typescript-rtti/typescript-rtti#16]
I need to differentiate between
```ts
class A {
async explicitType(): Promise<string> {
    if (process.env.A) {
      return null
    }
    return 'baz'
  }
async noExplicitType() {
    if (process.env.A) {
      return null
    }
    return 'baz'
  }
}
```

when I do 
```
console.log(bClass.getMethod('noExplicitType').returnType)
console.log(bClass.getMethod('explicitType').returnType)
```
they both return the same rtti structure.

I need to be able to recognize when the type is just guessed by TS and when it is explicitly written down by the user.

**Comment by rezonant** [comment]
Interesting, what is the use case there?

**Comment by capaj** [comment]
In decapi when I want to generate a Graphql type from the TS type, I need to mark it either nullable or non nullable.
Since the TS incorrectly infers `Promise<string>` for `noExplicitType`
![image](https://user-images.githubusercontent.com/1305378/154837627-634ff2b3-f967-472a-a8f5-0500b5ce3b3f.png)
I would like to default into marking such methods as nullable. At the moment on the decapi wip branch I just treat TS as the truth, because I have no way to know whether this is use who explicitly wrote the type or just TS trying to guess the type.

TODO line in decapi:  https://github.com/capaj/decapi/blob/0dc6969c800d9ec9db74ec5e3f46d756c2f676b1/src/services/utils/gql/types/inferTypeByTarget.ts#L67

**Comment by rezonant** [comment]
I see, so since Typescript doesn't infer `Promise<string | null>` you can't tell if the `return null` is present for the purposes of informing the nullability attribute. 

This sounds good and should be possible

**Comment by rezonant** [comment]
I think that the strictNullChecks was really the culprit here, but regardless-- `typescript-rtti@0.2.1` now supports detecting inference. Use `ReflectedMethod#returnTypeInferred` or `ReflectedFunction#returnTypeInferred` to determine if the return type of a method/function is inferred .
