### ISSUE TITLE
Bug: Generic type is reflected as class

### ISSUE THREAD

**Issue by capaj** [typescript-rtti/typescript-rtti#17]
```ts
class B {
  async floatNullable(): Promise<number | null> {
    return 10
  }
}

let bClass = reflect(B)

console.log(
  bClass
    .getMethod('floatNullable')
    .returnType.as('generic')
    .typeParameters[0].isUnion()
) // logs false, should be true

console.log(
  bClass
    .getMethod('floatNullable')
    .returnType.as('generic')
    .typeParameters[0].isClass()
) // logs true, should be false

```

tested in latest version 0.2.0

**Comment by rezonant** [comment]
Replication for `any` received instead of generic:
https://typescript-rtti.org/#aW1wb3J0IHsgcmVmbGVjdCB9IGZyb20gJ3R5cGVzY3JpcHQtcnR0aSc7CgpjbGFzcyBCIHsKICAgIGFzeW5jIGZsb2F0TnVsbGFibGUoKTogUHJvbWlzZTxudW1iZXIgfCBudWxsPiB7IAogICAgICAgIHJldHVybiAxMAogICAgfQp9CgpsZXQgYkNsYXNzID0gcmVmbGVjdChCKQoKY29uc29sZS5sb2coCiAgICBiQ2xhc3MuZ2V0TWV0aG9kKCdmbG9hdE51bGxhYmxlJykucmV0dXJuVHlwZQop

**Comment by capaj** [comment]
I am getting this locally, not just in the playground:
![image](https://user-images.githubusercontent.com/1305378/154952667-54f00e1a-baed-472d-ad90-c9ba5fe8b1bb.png)
![image](https://user-images.githubusercontent.com/1305378/154952709-deb35dd6-92e2-474e-bc04-decf69c465de.png)

**Comment by rezonant** [comment]
There are two issues. First, the website was giving `any` because it didn't understand `Promise` (because the libs weren't loaded). This issue is fixed

The second issue is that `number | null` is getting converted by TS to `number` before we get to it. That one is repeatable

**Comment by rezonant** [comment]
But I'm not sure how we can change that, `number` already contains `null` so `number | null` === `number`:

![image](https://user-images.githubusercontent.com/409140/154953284-d651eb12-01f3-4860-bd92-3b83d972e5ed.png)

**Comment by rezonant** [comment]
Oh, have you set `strictNullChecks` to `true` in your `tsconfig.json` ?

**Comment by rezonant** [comment]
Filed #19 to see if we can support null optin without strictNullChecks

**Comment by capaj** [comment]
I did not had that configured. Thanks. Would be worth adding this to the readme.
