### ISSUE TITLE
Reflect.hasMetadata is not a function

### ISSUE THREAD

**Issue by thefill** [typescript-rtti/typescript-rtti#26]
While using any of the examples provided I have encountered:
"TypeError: Reflect.hasMetadata is not a function"

Solution: add line
`import 'reflect-metadata';`

This is missing from the documentation.

**Comment by rezonant** [comment]
Good point, this has been addressed in the README now. Thanks!

**Comment by thefill** [comment]
> Good point, this has been addressed in the README now. Thanks!

a pleasure & thanks for an amazing package.

**Comment by rezonant** [comment]
Thank you! I'm glad it's useful!!
