### ISSUE TITLE
Uncaught TypeError: Type has kind generic, expected interface

### ISSUE THREAD

**Issue by khusamov** [typescript-rtti/typescript-rtti#59]
This code:

```typescript
import 'reflect-metadata'
import {reflect} from 'typescript-rtti';

interface IStoppable {
	stop(): void;
}

export declare type TStoppableKey = string;

interface IWithStoppable<S extends IStoppable = IStoppable> {
	stoppableMap: Map<TStoppableKey, S> | undefined;
}

console.log(reflect<IWithStoppable>().as('interface'))
```

generates such an error:

```
Uncaught TypeError: Type has kind generic, expected interface
    at ReflectedGenericRef.as (reflect.js:171:19)
    at index.ts:14:39
    at index.js:5:2
    at index.js:6:3
```

**Comment by rezonant** [comment]
That's expected, as the type itself is generic.

Resolve it as a generic, then get the interface from the baseType like so:

```typescript
reflect<IWithStoppable>().as('generic').baseType.as('interface')
```

See the example here: https://typescript-rtti.org/#fFYyfHsic291cmNlIjoiaW1wb3J0IHtyZWZsZWN0fSBmcm9tICd0eXBlc2NyaXB0LXJ0dGknO1xuXG5pbnRlcmZhY2UgSVN0b3BwYWJsZSB7XG5cdHN0b3AoKTogdm9pZDtcbn1cblxuZXhwb3J0IGRlY2xhcmUgdHlwZSBUU3RvcHBhYmxlS2V5ID0gc3RyaW5nO1xuXG5pbnRlcmZhY2UgSVdpdGhTdG9wcGFibGU8UyBleHRlbmRzIElTdG9wcGFibGUgPSBJU3RvcHBhYmxlPiB7XG5cdHN0b3BwYWJsZU1hcDogTWFwPFRTdG9wcGFibGVLZXksIFM+IHwgdW5kZWZpbmVkO1xufVxuXG5jb25zb2xlLmxvZyhyZWZsZWN0PElXaXRoU3RvcHBhYmxlPigpLmFzKCdnZW5lcmljJykuYmFzZVR5cGUuYXMoJ2ludGVyZmFjZScpKSIsImNvbXBpbGVyT3B0aW9ucyI6IiJ9

![image](https://user-images.githubusercontent.com/409140/166072312-2fcadfa3-3423-4ab2-9dd3-e59dd4356831.png)

**Comment by rezonant** [comment]
Note you can use `is('generic')` et al to test what kind of type reference you are dealing with. Useful if you need to support both generic and non-generic interfaces.

**Comment by khusamov** [comment]
Thanks!
