### ISSUE TITLE
Ability to expose parent interfaces

### ISSUE THREAD

**Issue by khusamov** [typescript-rtti/typescript-rtti#60]
How do I access the `type` property?

```typescript
import 'reflect-metadata'
import {reflect} from 'typescript-rtti';

interface ITyped {
	type: string;
}

interface IOrder extends ITyped {}

console.log(reflect<IOrder>().as('interface').reflectedInterface.properties) // []
```

**Comment by rezonant** [comment]
I think this is a bug, you are doing it right.

https://typescript-rtti.org/#fFYyfHsic291cmNlIjoiaW1wb3J0IHtyZWZsZWN0fSBmcm9tICd0eXBlc2NyaXB0LXJ0dGknO1xuXG5pbnRlcmZhY2UgSVR5cGVkIHtcblx0dHlwZTogc3RyaW5nO1xufVxuXG5pbnRlcmZhY2UgSU9yZGVyIGV4dGVuZHMgSVR5cGVkIHt9XG5cbmNvbnNvbGUubG9nKHJlZmxlY3Q8SU9yZGVyPigpLmFzKCdpbnRlcmZhY2UnKS5yZWZsZWN0ZWRJbnRlcmZhY2UpIC8vIFtdIiwiY29tcGlsZXJPcHRpb25zIjoiIn0=

**Comment by rezonant** [comment]
This will be available in the next release. You'll be able to access the classes/interfaces that an interface _extends_ in the same way that you access the classes/interfaces that a class _implements_, via `ReflectedClass#interfaces`.

**Comment by rezonant** [comment]
v0.6.1 is now out with this enhancement.
