### ISSUE TITLE
Add support for Typescript 4.7

### ISSUE THREAD

**Issue by Saghetti0** [typescript-rtti/typescript-rtti#82]
When trying to run `npm i typescript-rtti`

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: api@1.0.0
npm ERR! Found: typescript@4.7.4
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"^4.7.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"4.6" from typescript-rtti@0.8.0
npm ERR! node_modules/typescript-rtti
npm ERR!   typescript-rtti@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/waltermin/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/waltermin/.npm/_logs/2022-07-19T07_47_23_957Z-debug-0.log
```

Node version: 18.3.0
NPM version: 8.11.0
Typescript version: 4.7.4

**Comment by CristianPi** [comment]
@Saghetti0 downgrade your typescript version or do npm i --force, it should work with typescript 4.7

**Comment by Saghetti0** [comment]
Downgrading to Typescript 4.6 worked. Are there any plans to support the latest Typescript 4.7 though?

**Comment by rezonant** [comment]
Oof, we do support Typescript 4.7 already. This is an incorrect peer dep. Willfix!

**Comment by CristianPi** [comment]
mmm yes,i also have another problem with ts 4.7+

```bash
TypeError: Cannot read properties of undefined (reading 'length')
    at emitShebangIfNeeded (/home/cristian/IdeaProjects/climbo2/node_modules/typescript/lib/tsc.js:113681:79)
    at Object.writeBundle (/home/cristian/IdeaProjects/climbo2/node_modules/typescript/lib/tsc.js:110872:13)
    at printSourceFileOrBundle (/home/cristian/IdeaProjects/climbo2/node_modules/typescript/lib/tsc.js:110436:25)
    at emitJsFileOrBundle (/home/cristian/IdeaProjects/climbo2/node_modules/typescript/lib/tsc.js:110342:13)
    at emitSourceFileOrBundle (/home/cristian/IdeaProjects/climbo2/node_modules/typescript/lib/tsc.js:110265:13)
    at forEachEmittedFile (/home/cristian/IdeaProjects/climbo2/node_modules/typescript/lib/tsc.js:110004:34)
    at Object.emitFiles (/home/cristian/IdeaProjects/climbo2/node_modules/typescript/lib/tsc.js:110245:9)
    at emitWorker (/home/cristian/IdeaProjects/climbo2/node_modules/typescript/lib/tsc.js:117534:33)
    at /home/cristian/IdeaProjects/climbo2/node_modules/typescript/lib/tsc.js:117511:72
    at runWithCancellationToken (/home/cristian/IdeaProjects/climbo2/node_modules/typescript/lib/tsc.js:117606:24)
```

**Comment by rezonant** [comment]
I apparently can't keep track of TS versions. The compiler API changes are in typescript@next which is 4.8. I've bumped the versions on `main` to 4.7 and added it to corpus testing.

@CristianPi the unit test suite seems to pass just fine with 4.7, corpus test suite is running now on CI. If corpuss passes without exposing the above problem, would you be willing to set up an isolated test case of that issue? Otherwise if your code is open source, we can add it to the corpus test suite.

**Comment by CristianPi** [comment]
> I apparently can't keep track of TS versions. The compiler API changes are in typescript@next which is 4.8. I've bumped the versions on `main` to 4.7 and added it to corpus testing.
> 
> @CristianPi the unit test suite seems to pass just fine with 4.7, corpus test suite is running now on CI. If corpus passes without exposing the above problem, would you be willing to set up an isolated test case of that issue? Otherwise if your code is open source, we can add it to the corpus test suite.
> 
> First test run with 4.7 is at https://app.circleci.com/pipelines/github/typescript-rtti/typescript-rtti/353/workflows/415f099c-2dc7-4ee6-9f43-fe9ea0be8eda

With the new version 0.8.2 and upgrading to typescript 4.7.x the error is gone, so i wouldn't lose any more time on this, also because i have no idea on how to reproduce that.

**Comment by capaj** [comment]
oof I am using with TS 4.7.4 in prod. What's the recommended TS version? This should be added to the readme somewhere to the top so that people don't miss it.

**Comment by rezonant** [comment]
The peer deps does specify supported TS versions, but indeed adding a supported TS versions to README would also be good.

@capaj Is everything working as expected with 4.7? There were no changes required in the test suite so it should, I just need to update the TypeORM version before I can officially say it's fine.

**Comment by rezonant** [comment]
Peer deps are updated in typescript-rtti@0.8.3.
