### ISSUE TITLE
Directory import is not supported resolving ES modules 

### ISSUE THREAD

**Issue by josdejong** [typescript-rtti/typescript-rtti#94]
I have a TS project that outputs ES modules. As soon as I use `CallSite`, I get the following error when running the application:

```
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '[...]\node_modules\typescript-rtti\dist' is 
not supported resolving ES modules imported from [...]\build\index.js
Did you mean to import typescript-rtti/dist/index.js?
```

Halfway the output generated by ttsc, the following import is inserted in the code:

```js
import * as LΦ_0 from "typescript-rtti/dist";
```

This isn't a valid ES modules import. When I change the import to `"typescript-rtti/dist/index.js"` or `"typescript-rtti"`, all works fine. Is it possible to generate this import with /index.js at the end? That would make it both valid CommonJS and ESM.

**Comment by rezonant** [comment]
In 0.9.x, we are now leaving .js on imports which may resolve this issue, but there are plenty of other ESM related issues being worked out. ESM is the current focus for development. Please reopen if you are still getting no-extension imports from the library

**Comment by josdejong** [comment]
👍
